# Load songs and make PR scheduled

name: Scheduled loading songs

# Run 1:00 pm in JST everyday
on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  load-songs-from-easite:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.1
    - name: Install dependencies
      run: yarn install
    - name: Load songs
      run: yarn load

    - name: Make diff
      id: diff
      run: |
        git add -N .
        git diff --name-only --exit-code
      continue-on-error: true
      
    - name: Create new branch
      run: |

    # make PR if diff exists
    - name: Make Pull Request
      env:
        TZ: 'Asia/Tokyo'
      run: |
        git switch -c auto/stores/$(date +'%Y-%m-%d')
        git add .
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"
        git commit -m "automatically generate songs store."
        git push origin auto/stores/$(date +'%Y-%m-%d')
        gh pr create -B master -t "[automated] Update songs at $(date +'%Y-%m-%d')" -b 'This PR is automatically generated. Check diff about songs.'
      if: steps.diff.outcome == 'failure'
